name: flutter_note
description: Fluuterの勉強に使うサンプルコードです
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

scripts:
  doc: dart scripts/doc.dart

dependencies:
  google_fonts:
  flutter_slidable:
  freezed_annotation:
  liveroom:
  percent_indicator:
  go_router:
  flutter_riverpod:
  flutter:
    sdk: flutter
  pixel_color_image: 1.2.2
  web_socket_channel:
  yuix:
  firebase_core:
  firebase_analytics:
  device_preview:

dev_dependencies:
  freezed:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/
    - assets/google_fonts/
  uses-material-design: true
